version: '2'
services:
  db:
    environment:
      PGDATA: /opt/test_data
    volumes: 
      - /opt/test_data:/opt/test_data
    image: postgres
    restart: always
  web:
    build: . 
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always  